### ISSUE TITLE
Reset filter when going to /ui/locks

### ISSUE THREAD

**Issue by jefrww** [freiheit-com/kuberpult#1033]
When you search for a specific service in the deployments, that filter persists even if you switch to `/ui/locks` where you most likely want to see all existing locks.
So a better UX probably would be, to clear the `Application Name` filter when switching pages.
In case someone wants to search the locks by application, they could still do that explicitly on `/ui/locks` afterwards.

**Comment by sven-urbanski-freiheit-com** [comment]
I agree the current UX is not ideal.

We could for example:
* Keep the filter, but add a button to clear it more easily (and make the user aware of the filter), like "You are filtering for app X, reset?"
* Reset the filter every time we switch from locks to home or back, but allow filtering on the locks page still
* Store a separate query parameter for the filter in the locks page and the home page, so they both filter, but are not linked together like they are now.
* ...
