### ISSUE TITLE
Allow App names with length > 39

### ISSUE THREAD

**Issue by jdvgh** [freiheit-com/kuberpult#1182]
Hi,
I noted that there's an arbitrary length restriction on the length of the application name to 39 characters.
In our application we have microservices which have a name with length of 40-45 characters.
And who knows whether they get longer in the future.
I don't think it makes sense to trim a character of every service for just this application, as this could also impose `uniqueness` issues.

The change was introduced with #814.
From Argo-CD side it looks like this is possible to have quite long application names, so this should not conflict:
https://github.com/argoproj/argo-cd/pull/7468

Proposal:
So maybe just add 31 more characters as a buffer.

**Comment by jdvgh** [comment]
Thanks for the fast feedback.
I'll have a deeper look next week!

**Comment by jdvgh** [comment]
Added a comment here
https://github.com/freiheit-com/kuberpult/pull/1183#issuecomment-1840790228
Should be possible with configuring ArgoCD correctly.

**Comment by bjoern-michaelsen-freiheit** [comment]
Was this closed with https://github.com/freiheit-com/kuberpult/pull/1183 ?

**Comment by jdvgh** [comment]
@jdvgh no worries. Thanks for the feedback! I included it in my PR - feel free to check it out.
