### ISSUE TITLE
delete them all button does not work

### ISSUE THREAD

**Issue by ssp** [freiheit-com/kuberpult#1188]
I did this

* lock two services and apply that together
* click the trash icon on one of the locks
→ The »Delete App Lock« item appears in the cart and includes the nice »Delete them all!« button
* click the »Delete them all!« button

expected

* deletion of the second application lock is added to the cart

actual

* nothing happens

**Comment by ssp** [comment]
Additional observation: trying to add the second lock deletion to the cart separately does not work either in this situation, may be a duplicate of #1049

**Comment by bjoern-michaelsen-freiheit** [comment]
> Additional observation: trying to add the second lock deletion to the cart separately does not work either in this situation, may be a duplicate of #1049

Indeed it is:
The duplicate detection in addAction is somewhat nonchalant with application locks: it does compare envs, but not the targeted application. Thus two applications lock for different applications are currently considered to be dupes.

Fix incoming.

**Comment by bjoern-michaelsen-freiheit** [comment]
after triage: closing as duplicate (special case) of #1049.
