### ISSUE TITLE
The initial health check for the CD service should be increased.

### ISSUE THREAD

**Issue by WladiTP** [freiheit-com/kuberpult#1191]
I’ve encountered the following issue: when updating the chart for the CD service, I receive an error because the health check isn’t functioning after 5 seconds. If I delay the initial health check by 60 seconds, the update works. Could you delay the initial health check defined in the chart?

**Comment by sven-urbanski-freiheit-com** [comment]
The health probes can be configured via `cd.probes.readiness.initialDelaySeconds` see here: https://github.com/freiheit-com/kuberpult/blob/3812dcb365beedf7ed1f6ae28baa2af616cbfab9/charts/kuberpult/values.yaml.tpl#L60

Or are you referring to the default value?

As of know the initial delay required depends mainly on the size of the manifest repo.

**Comment by bjoern-michaelsen-freiheit** [comment]
Seems this should be closed?

**Comment by sven-urbanski-freiheit-com** [comment]
Closing this, because we added a bunch of options to configure the health check here: https://github.com/freiheit-com/kuberpult/pull/1382/files
