### ISSUE TITLE
The backend id given needs to be updated if the backend id changes

### ISSUE THREAD

**Issue by gmestre-freiheit** [freiheit-com/kuberpult#1376]
In case kuberpult is updated, we need to give the id, which can happen on some redeployments.
This means that the author no longer appears in the commits in the manifests repository unless we also update this id manually and in case someone forgets we might loose the author of the changes made via kuberpult for a while. This breaks traceability on these cases.

It is referred here how to fetch the id and use it: https://github.com/freiheit-com/kuberpult/blob/main/charts/kuberpult/values.yaml.tpl#L183-L191

An alternative to this would be that the kuberpult backend service fetches the id on startup, which could be implemented for multiple cloud providers, using their sdk and if the cloud provider is not one supported yet we could use the old approach still.
For example for Google Cloud you can find here the golang library: https://pkg.go.dev/google.golang.org/api/compute/v1#BackendService (not 100% sure if it is the right struct this one)

**Comment by sven-urbanski-freiheit-com** [comment]
We have a new helm parameter for that: https://github.com/freiheit-com/kuberpult/pull/1437 @gmestre-freiheit please take a look. I think with that we can close this issue.
