### ISSUE TITLE
issue while upgrading from v2.22 to v.2.27

### ISSUE THREAD

**Issue by GurayCetin** [freiheit-com/kuberpult#1571]
We are using renovate to upgrade versions for kuberpult on montly basis, and trying to upgrade v2.27 from v.2.22, but it is asking for service account named k8sname that i am not aware it before. It's not included in helm configuration to manage kuberpult on gke cluster.  

`33 FailedCreate: Error creating: pods "kuberpult-cd-service-698d47c756-" is forbidden: error looking up service account commons/k8sname: serviceaccount "k8sname" not found`

**Comment by florianmutter** [comment]
Seems like some database feature was added. I cannot find any documentation on this and the release log does only mention sqlite added and cloudsql added.

**Comment by sven-urbanski-freiheit-com** [comment]
Bugfix is on the way. The DB feature is still early work in progress, and should not have been the default in the helm chart.

In the meantime, the workaround would be to set `cd.db.dbOption: "NO_DB"` in the helm chart. However, the helm-chart parameters may still change in the future, so I would suggest to wait for the next kuberpult release.

**Comment by sven-urbanski-freiheit-com** [comment]
Fixed in https://github.com/freiheit-com/kuberpult/releases/tag/v2.30.1
