### ISSUE TITLE
Reliably update the ui and keep the user informed about potential token issues

### ISSUE THREAD

**Issue by ssp** [freiheit-com/kuberpult#1689]
Me and my PO are occasionally running into situations where kuberpult looks just fine but displays an old deployment state. This causes confusion because commits that were merged hours ago do not appear or becuase versions that should be on production already seem not to be.

What _seems_ to happen in these situations is that reloading kuberpult will briefly open a login window and then reload the _current_ state of the system (which then often matches the expectation).

So my theory is that kuberpult at some stage stops being able to load the current state from its backend. As I briefly see the authentication window during this process I assume this may have to do with some expired token.

Whatever the reason is: i would expect kuberpult a) to try a bit harder to keep my token in a working state and b) if it ends up in a situation where it cannot update its data to make this obvious to me on the screen so I am not confused and can reload the page myself.

**Comment by sven-urbanski-freiheit-com** [comment]
I think we're relying on the "StreamOverview" endpoint to be intact and if that breaks... well then we get what you described.
We should retry that connection more, see https://github.com/freiheit-com/kuberpult/blob/e766eff9ff4347b8e478e6706ffd372307ec50cb/services/frontend-service/src/ui/App/index.tsx#L89

**Comment by sven-urbanski-freiheit-com** [comment]
Ref: SRX-EG5JZK
