### ISSUE TITLE
Add link to ArgoCD

### ISSUE THREAD

**Issue by ssp** [freiheit-com/kuberpult#204]
As the state of the cluster can differ from that seen in kuberpult, it could be helpful to have link to ArgoCD for the service on a stage to quickly verify that the cluster actually has the state represented in kuberpult.

**Comment by hannesg** [comment]
@sven-urbanski-freiheit-com , do you want to take this to the UX meeting?

**Comment by sven-urbanski-freiheit-com** [comment]
This issue becomes more urgent when we add canary support
