### ISSUE TITLE
"Empty" apps when adding manifests for new environments

### ISSUE THREAD

**Issue by jonaswittbrodt** [freiheit-com/kuberpult#2051]
## Current behavior
When publishing a release of an application that contains manifests for environments to which the application is not yet deployed kuberpult immediately adds the application to the overview for all environments for which a manifest exists (without a version, so nothing is actually deployed). This leads to the creation of "empty" argo applications, "Unknown" rollout status in the UI, etc.

## Expected behavior
The application is only added to the overview cache for an environment when it is first deployed there (e.g. by a releastrain or a manual deployment).

**Comment by sven-urbanski-freiheit-com** [comment]
Ref: SRX-R9Q5YN

**Comment by sven-urbanski-freiheit-com** [comment]
Fixed in https://github.com/freiheit-com/kuberpult/pull/2160
