### ISSUE TITLE
Canary Support

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#206]
# For microservices:
We could use argo rollouts: https://argoproj.github.io/argo-rollouts/ / https://argoproj.github.io/argo-rollouts/features/specification/
This would only require changes in manifests, no feature changes.

Maybe consider https://flagger.app/

Maybe first decide what to do as tests!

Also consider that progressive rollouts might be good!

# For apps:
* maybe assign apps to specific user groups. This could be done with an extra environment ("canary-prod-test") in kuberpult.
* maybe add a specific system test to check firebase errors

**Comment by sven-urbanski-freiheit-com** [comment]
For apps: maybe assign apps to specific user groups. This could be done with an extra environment ("canary-prod-test") in kuberpult

**Comment by hannesg** [comment]
None of the proposed solutions need any tooling from kuberpult -> closing for now
