### ISSUE TITLE
Bug: Skip version on release dialog

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#288]
Sometimes not every release version exists in kuberpult for a given service.
Eg
Version 1: Exists
Version 2: Does not exist
Version 3: Exists

In the release dialog, when viewing version 1 and clicking the right arrow, it should jump to version 3, not 2.

Note that in reality, the gap can be much bigger!

**Comment by tameremad** [comment]
Can you add a method to reproduce?
