### ISSUE TITLE
Kuberpult Calls streamOverview for every cart addition/deletion

### ISSUE THREAD

**Issue by tameremad** [freiheit-com/kuberpult#298]
# bug
kuberpult is calling the streamOverview request on every modification to the cart. 

# expected behavior
streamOverview is only called once on loading / reloading

![image](https://user-images.githubusercontent.com/88655074/184855622-9c2695c2-6fcd-42ae-8292-6ce7624a805b.png)

**Comment by hannesg** [comment]
The call is very cheap on the backend. In some configurations, this is called every 30 seconds. I would not spend too much time on that as long as it doesn't cause problems.
