### ISSUE TITLE
Automatically deployed queue after deleting log without noticable warning

### ISSUE THREAD

**Issue by ghost** [freiheit-com/kuberpult#333]
Maybe I overlooked it, bit in that case i feel it would not be prominent enough. Good would be a hint with an unchecked checkbox saying `do you want to additionally remove the queue/deploy all versions from queue`. Default should be that this is not happening automatically, since we have had this problem now multiple times that the bugfix for the lock was not deployed because it was not part of the queue, but the bug itself. I do not see a good reason for this behaviour of deploying the queue automatically at this point

**Comment by sven-urbanski-freiheit-com** [comment]
tbh I'd like to remove queues entirely. But I'm not sure if we can get there quickly, so we will re-think the warnings that are shown.

**Comment by sven-urbanski-freiheit-com** [comment]
the unexpected lock behavior (deploying a queue after deleting a lock) is removed in v 0.4.47: https://github.com/freiheit-com/kuberpult/blob/main/CHANGELOG.md#0447
