### ISSUE TITLE
Kuberpult does not update on remote changes automatically

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#368]
When someone changes something in the manifest manually, kuberpult does not automatically recognize this (neither on backend nor in the UI).

We need a way to detect remote changes (in the manifest repo) and update the backend and frontend according.

**Comment by tameremad** [comment]
a refresh doesn't work for this? bc the backend will stay the same, correct?

**Comment by sven-urbanski-freiheit-com** [comment]
yes, correct

**Comment by hannesg** [comment]
I will close this for now. Remote changes happen like once a year and it's rarely an issue. Please reopen if you can work on this.
