### ISSUE TITLE
Deployment was not deleted after deploying the "undeploy" version

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#388]

**Comment by sven-urbanski-freiheit-com** [comment]
Note: the old manifest file is used, that is the error. We need to remove/empty it

**Comment by sven-urbanski-freiheit-com** [comment]
Manual workaround: Empty the manifest file in the manifest-repo manually (needs to be done in all envs). Otherwise argoCd will sync to the old version

**Comment by sven-urbanski-freiheit-com** [comment]
bugfix: https://github.com/freiheit-com/kuberpult/pull/412

**Comment by hannesg** [comment]
Closed for #412
