### ISSUE TITLE
Improvement: Release trains from arbitrary sources

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#401]
Right now, the source of a release train needs to be configured in the config.json file.
It would improve readability, if the source could be specific while calling the endpoint.
Instead of
`curl -X PUT "https://kuberpult.example.com/environments/production/releasetrain" --data-binary "${signature}"`
it could be
`curl -X PUT "https://kuberpult.example.com/environments/production/releasetrain/from/integration" --data-binary "${signature}"`

This would make it more obvious what a release train does, and it would be easier to change.

**Comment by hannesg** [comment]
Is that something that actually happens? We are also showing a warning if you skip stages, so why help people doing it?
