### ISSUE TITLE
Undeploy not working when app is not deployed everywhere

### ISSUE THREAD

**Issue by tobias18121994** [freiheit-com/kuberpult#451]
After we tried to Undeploy a service we get this error in the kuberpult cd service

`{"severity":"ERROR","timestamp":"2023-01-03T10:24:53.864543005+01:00","logger":"grpc_server","caller":"service/lock.go:108","message":"grpc.internal","grpc.start_time":"2023-01-03T10:24:53+01:00","system":"grpc","span.kind":"server","grpc.service":"api.v1.BatchService","grpc.method":"ProcessBatch","error":"could not apply transformer: UndeployApplication: error cannot un-deploy application 'update-region-claims-cronjob' the release 'azproductionbase' is not un-deployed","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"/__w/kuberpult/kuberpult/services/cd-service/pkg/service/lock.go","line":"108","function":"github.com/freiheit-com/kuberpult/services/cd-service/pkg/service.internalError"},"stacktrace":"github.com/freiheit-com/kuberpult/services/cd-service/pkg/service.internalError\n\t/__w/kuberpult/kuberpult/services/cd-service/pkg/service/lock.go:108\ngithub.com/freiheit-com/kuberpult/services/cd-service/pkg/service.(*BatchServer).ProcessBatch\n\t/__w/kuberpult/kuberpult/services/cd-service/pkg/service/batch.go:189\ngithub.com/freiheit-com/kuberpult/pkg/api._BatchService_ProcessBatch_Handler.func1\n\t/__w/kuberpult/kuberpult/pkg/api/api_grpc.pb.go:277\ngopkg.in/DataDog/dd-trace-go.v1/contrib/google.golang.org/grpc.UnaryServerInterceptor.func1\n\t/github/home/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.34.0/contrib/google.golang.org/grpc/server.go:157\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1117\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1\n\t/github/home/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:31\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1.1\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1120\ngoogle.golang.org/grpc.chainUnaryInterceptors.func1\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1122\ngithub.com/freiheit-com/kuberpult/pkg/api._BatchService_ProcessBatch_Handler\n\t/__w/kuberpult/kuberpult/pkg/api/api_grpc.pb.go:279\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1283\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:1620\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/github/home/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:922"}
`
The service is still in the Prepare to Undeploy state.

**Comment by sven-urbanski-freiheit-com** [comment]
> error cannot un-deploy application 'update-region-claims-cronjob' the release 'azproductionbase' is not un-deployed"

The service must have the same undeploy-version deployed on all environments.
As of now you need to make sure this is the case, otherwise "undeploy" will not work.
But I think that doesn't help you, because you don't want to deploy it on 'azproductionbase'.

Solution is probably to skip the environments where this particular app is not deployed: 
 https://github.com/freiheit-com/kuberpult/blob/main/services/cd-service/pkg/repository/transformer.go#L427

**Comment by sven-urbanski-freiheit-com** [comment]
The bugfix is merged and a new version has just been released @tobias18121994 https://github.com/freiheit-com/kuberpult/releases/tag/0.4.61

Closing this issue now.
