### ISSUE TITLE
V2 version of UI is inaccessable if AzureAuth is enabled

### ISSUE THREAD

**Issue by qr4** [freiheit-com/kuberpult#468]
Accessing the `/v2/home` path results in this response if AzureAuth is enabled:

```
Invalid authorization header provided
```

**Comment by mouhsen-ibrahim** [comment]
We have a story for this https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-NBqxle4E6_yXdF2J1Xo/

**Comment by medo-freiheit** [comment]
solved #480
