### ISSUE TITLE
Annotation "nginx.ingress.kubernetes.io/force-ssl-redirect" leads to an "ingress.yaml" template error

### ISSUE THREAD

**Issue by geeko4711** [freiheit-com/kuberpult#488]
I assume there is an error in the ingress.ymal template. If we add the following annotation to the terraform  code:
**nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'** 
we get the template error "executing "kuberpult/templates/ingress.ymal" at <.Values.ingress.annotations>: range can't iterate over "nginx.ingress.kubernetes.io/force-ssl-redirect": true

--- ingress.yaml snipset ...

kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/cluster-issuer: letsencrypt
**{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
{{- end }}**
  name: kuberpult
spec:

{{}}

**Comment by mouhsen-ibrahim** [comment]
Hi @geeko4711 thanks for creating this issue, `ingress.annotations` should be an object in your terraform code, if you set it using ```
set {
  name = "ingress.annotations"
  value = "nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'"
}
```
It will be treated as a string and the template will not compile correctly. You need to provide it as an object, I'm already trying to figure this out, I'll add a new comment once I manage to solve it

**Comment by geeko4711** [comment]
@mouhsen-ibrahim any update here?

**Comment by hannesg** [comment]
@geeko4711 

I think the easier and simpler solution is not to go through the woes of helm value parsing but pass the values directly in a values.yaml

```
values [ <<-EOT
  ingress:
    annotations:
      "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
  EOT
]
```
