### ISSUE TITLE
Removing applications from single stages

### ISSUE THREAD

**Issue by hannesg** [freiheit-com/kuberpult#50]
As a developer, I want to remove an application from a single stage if it is not needed anymore.

Deploying an empty manifest currently doesn't work reliably. Also because we tell argocd to keep skip empty directories.

We should configure the argocd apps to actually work with empty manifests when the manifests are really empty.

**Comment by sven-urbanski-freiheit-com** [comment]
Current workaround:
Instead of an empty manifest, define a configmap (or any kubernetes entity).

**Comment by sven-urbanski-freiheit-com** [comment]
I think we need a button for this.
Deleting things in any automated way sounds dangerous.
Suggestion:
* Add a button "Delete app from env"
* When clicked, kuberpult deletes the files, and communicates to argo that we really want to delete them (`AllowEmpty` field).

**Comment by sven-urbanski-freiheit-com** [comment]
https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-NWmdEVwpo8pfELTgPro/

**Comment by sven-urbanski-freiheit-com** [comment]
This is possible now via the API.
UI adaptation still need to be done https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-NXAUHlQaHH1yrO9nk1P/

**Comment by sven-urbanski-freiheit-com** [comment]
This is now implemented in the UI with the button "Remove Environment From App":
![Screenshot from 2023-09-08 13-47-38](https://github.com/freiheit-com/kuberpult/assets/3481382/6f497c63-d154-4311-a9fa-348f7c1426fe)
