### ISSUE TITLE
Sorting Stage names in Kuberpult

### ISSUE THREAD

**Issue by Murtaza-Solangi** [freiheit-com/kuberpult#536]
Is there a way to sort the stages listed in Kuberpult?

**Comment by hannesg** [comment]
Moin

Not yet in the UI. What exactly do you want to achieve? Can you write a user story?

**Comment by sven-urbanski-freiheit-com** [comment]
The stages are automatically sorted in most places, by "distance to upstream". Meaning, dev comes first, then staging, then production.
@Murtaza-Solangi please include a screenshot where the stages are not sorted as you expected it.

**Comment by Murtaza-Solangi** [comment]
Hi, Our stages look like the following:
[Image](https://imgur.com/a/SbcSars)
It would be nice if we could arbitrarily change the sorting of these stage names

**Comment by sven-urbanski-freiheit-com** [comment]
@Murtaza-Solangi your screenshot is from the old UI. In the newest version the old UI is already completely gone.
Depending on your version of kuberpult, you can reach the new ui either directly under `/` (with versions >= 0.4.62). With older versions it is reachable under `/v2/home`.

In the new UI we sort (and color!) environments by "distance to upstream" (meaning, how far is the environment away from "latest:true" in the change of release trains).

New UI:
![2023-03-07_19-08_release_new](https://user-images.githubusercontent.com/3481382/232759174-d2c85674-a89d-4f6e-af65-77654527e9c5.png)

So I don't think this is an issue anymore.
If it still is, please re-open @Murtaza-Solangi .

**Comment by hannesg** [comment]
I would really like to avoid adding more configuration. Can we somehow calculate the correct order?
