### ISSUE TITLE
Git db compression fails

### ISSUE THREAD

**Issue by tameremad** [freiheit-com/kuberpult#551]
# Issue: 
Release train workflow failed. the traces give out `git.repack` and lead to `maybeGc` 
https://app.datadoghq.eu/logs?query=service%3Akuberpult-cd-service%20status%3Aerror%20&additional_filters=%5B%7B%7D%5D&cols=host%2Cservice&index=%2A&messageDisplay=inline&spanID=7196714735387314404&stream_sort=time%2Cdesc&viz=stream&from_ts=1676369423529&to_ts=1678961423529&live=true

# Possible reasons: 
`maybeGc` is running the git db compression. 
This compression takes extra resources. That could be too much. 
* https://github.com/freiheit-com/kuberpult/blob/f973533c179a846a000a23c4a0177ec41a493e26/services/cd-service/pkg/repository/repository.go#L659-L676

# Expected behavior:
kuberpult requests don't fail because of this compression.

# solutions
* maybe run the compression periodically? in a less busy time?
* run the compression more often? 
* remove the compression altogether? and do more pod restarts?

**Comment by sven-urbanski-freiheit-com** [comment]
We have a story for this (just talked about this with Hannes) https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-NR2eQPxASwlooQBhXIe/
