### ISSUE TITLE
Rolling back multiple services to releases that are hidden from the Home page takes a lot of time 

### ISSUE THREAD

**Issue by tameremad** [freiheit-com/kuberpult#567]
if a release is hidden from the homepage, deploying it requires a visit to the history page of a service and then clicking the desired release, and then deploying.

repeating that for a few services at once could be inefficient. 

First, check if this is only a rare occurrence. 
* Look at the manifest repo data and see how often rolling back happens.

**Comment by sven-urbanski-freiheit-com** [comment]
This should be rather rare.
Closing it now until someone sees this happen in action.
