### ISSUE TITLE
Unlocking an environment with `upstream: latest` configuration should update all services in the environment to their most recent releases

### ISSUE THREAD

**Issue by qr4** [freiheit-com/kuberpult#576]
As of now, if we create a lock on an environment with an `upstream: latest` configuration, and services receive new releases while the lock is active, services wont be updated when the lock is released.
This is imo inconsistent with the idea of the `upstream: latest` configuration. Instead, when such an environment is unlocked, all services should be updated to their most recent release.

**Comment by sven-urbanski-freiheit-com** [comment]
I think we should handle app locks and env locks the same, meaning also if an app is unlocked, deploy it.

This should be obvious from the UI, we need some hints there, to make the user aware something will be deployed.

**Comment by hannesg** [comment]
We had so many issues with people wondering why things change after locks are removed. I really don't want to introduce this back for single cases as that would be even more confusing ( why is this env updating but not the other? ).

One compromise I could think of is that you can specify on unlocking whether you want the update to happen. That would be consistent.

**Comment by florianmutter** [comment]
Is there now a way to manually deploy the latest release of everything in a env? If for example a lock was in place for quite some time and now we want to remove it and get back to the latest release in dev?

**Comment by sven-urbanski-freiheit-com** [comment]
yes, the solution is to run a release train to dev.
This takes the latest releases and deploys them all to dev.
We recommend doing this whenever you unlock the dev environment. @florianmutter

**Comment by florianmutter** [comment]
Is there a button to do this? Running a curl command with keys and stuff seems rather inconvenient
