### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#608]
`{"msg":"error in streamoverview","error":{"code":2,"metadata":{"headersMap":{"access-control-allow-credentials":["true"],"access-control-allow-origin":["*"],"access-control-expose-headers":["Access-Control-Allow-Credentials, Vary, Content-Type, Date, Access-Control-Allow-Origin, grpc-status, grpc-message"],"alt-svc":["h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],"content-type":["application/grpc-web+proto"],"date":["Wed, 05 Apr 2023 09:07:59 GMT"],"vary":["Origin"],"via":["1.1 google"]}}}}`

**Comment by sven-urbanski-freiheit-com** [comment]
reported by @obreitwi
![image (3)](https://user-images.githubusercontent.com/3481382/230036501-bbef7ac5-d8c3-4706-9c25-5f8d746efc67.png)

**Comment by tameremad** [comment]
could be related to this: https://stackoverflow.com/questions/58215104/whats-the-neterr-http2-protocol-error-about

**Comment by sven-urbanski-freiheit-com** [comment]
![image (5)](https://github.com/freiheit-com/kuberpult/assets/3481382/23da50c1-e292-454c-8c8e-76fecdd13a17)

@gu-freiheit has reported a similar issue

**Comment by bjoern-michaelsen-freiheit** [comment]
@sven-urbanski-freiheit-com This seems old and I havent seen it in recent releases, can it be closed?
