### ISSUE TITLE
display kuberpults version number in UI

### ISSUE THREAD

**Issue by sven-urbanski-freiheit-com** [freiheit-com/kuberpult#610]
We already have the version in `GetFrontendConfigResponse`. We just have to display it, e.g. in the html `title` or as a tooltip above the whale (top left).

https://github.com/freiheit-com/kuberpult/blob/main/pkg/api/api.proto#L134

**Comment by tameremad** [comment]
https://github.com/freiheit-com/kuberpult/pull/668
