### ISSUE TITLE
Allow locking of all environments in an environment group

### ISSUE THREAD

**Issue by qr4** [freiheit-com/kuberpult#611]
Kuberpult already supports triggering release trains from / to env groups. 

I would like to see to also lock all environments in an envgroup. An example usecase would be to lock all production environments at once.

**Comment by sven-urbanski-freiheit-com** [comment]
this works now. Both in the UI and in the REST endpoint. See https://github.com/freiheit-com/kuberpult/blob/main/infrastructure/scripts/create-testdata/delete-env-group-lock.sh
