### ISSUE TITLE
Use IAP auth header instead of defaults

### ISSUE THREAD

**Issue by hannesg** [freiheit-com/kuberpult#710]
IAP auth configuration is easy to get wrong: We silently default to the default user when the gke project number or gke backend id is not set. Maybe we should just still accept the IAP header if this is missing.

**Comment by sven-urbanski-freiheit-com** [comment]
If we do that, I think we need to make it clear that we are not really sure that it is this person. People tend to rely on kuberpult to have something like an audit log. In that area, we need to be really sure that what we write into git is really true.
Maybe we could do something like what github does when you don't have the right email associate with your account:
![image](https://github.com/freiheit-com/kuberpult/assets/3481382/3a91d3f2-459d-4376-a5bc-4b317065b5d8)
They just add "unverified" to the username.

**Comment by sven-urbanski-freiheit-com** [comment]
We now have this PR https://github.com/freiheit-com/kuberpult/pull/1437/files
so I would consider this done.
