### ISSUE TITLE
Showing version nr

### ISSUE THREAD

**Issue by MiguelFMartins** [freiheit-com/kuberpult#809]
For certain operations it shows the version number it will use/it is about, however nowhere does it show what the version number actually stands for (commit, time, etc).
A suggestion would be to show the version number on the "View History" page. Or replace the version number with the commit in question on the messages if the version number is supposed to be only internally significant.
![image](https://github.com/freiheit-com/kuberpult/assets/104832857/5d02dcdb-4ad9-4d17-89a2-ad927a30b3ba)

**Comment by sven-urbanski-freiheit-com** [comment]
My idea was to never show the version number.
The number is not something that a user of kuberpult has any connection to (outside of kuberpult).
I already removed the version number from a couple of places, but there are more, as your example shows.
It's not as simple as replacing `.version` with `.commitId`, but we will improve this.

**Comment by sven-urbanski-freiheit-com** [comment]
This is solved with 1.5.0
