### ISSUE TITLE
Should we provide a new tab "Action History" ?

### ISSUE THREAD

**Issue by wuyuting** [freiheit-com/kuberpult#892]
As an user, I want to see the action history which I have applied, it could be pretty useful for the audit purpose, can we provide this function ? or I can try to raise a PR.

**Comment by hannesg** [comment]
Yes indeed. The For audits, we usually analyze the repository directly. There are a few caveats why this might be hard to implement:

1. The only data we have is the git commit history.
2. We avoid fetching more than we need atm, so it's incomplete on the server.
3. Even if you have all commits, they only encode changes but not the high-level actions that caused them.

That being said. I like the idea but it's hard to get right.

**Comment by wuyuting** [comment]
Got it, thanks for your reply,  hope we can do it when there is a better opportunity.
