### ISSUE TITLE
Please display release hash on history page

### ISSUE THREAD

**Issue by obecker** [freiheit-com/kuberpult#951]
The kuberpult default home page (`/ui/home`) shows a release hash number for every built artifact. It would be very helpful if this hash would also be displayed on the history page of each artifact (i.e. on `/ui/home/releases/<name>`).

<img width="511" alt="Bildschirmfoto 2023-09-18 um 15 40 38" src="https://github.com/freiheit-com/kuberpult/assets/197628/2dbcd072-82e2-4afb-9ce9-4fa331c350c3">

**Comment by sven-urbanski-freiheit-com** [comment]
Implemented in 1.5.0
