### ISSUE TITLE
Epic: groups of applications

### ISSUE THREAD

**Issue by hannesg** [freiheit-com/kuberpult#98]
The first version of kuberpult was designed to work for a group of ~30 people organized in 5 teams. We are now seeing adoption for groups of > 50 people that are working less cohesively.

# User Stories

*Alice* is a senior developer, kind of an architect. She works across multiple teams and wants to have an overview of the releases of multiple teams.

*Bob* is a software engineer and experienced in kuberpult. He manages the software rollout of his team.

*Clair* is a junior software engineer and uses kuberpult only lightly. She only uses kuberpult very occasionally when something is not working as expected.

1. *Clair* is currently overwhelmed with the overview. Her team's name starts with 'k' and so she has to scroll down exactly to the right position. She would really like to have a bookmark where she could exactly view her own teams applications and nothing else.

2. *Bob* is unhappy that the argocd notification channel in slack is shared by multiple teams. He constantly gets notifications from the seven other teams that are sharing the kuberpult instance and with every additional team, it gets worse.

3. *Bob* also manages the release cycle of his teams applications. Coordinating the release cycle with multiple teams is hard because there is only one release train in kuberpult although there is no reason to release everything together.

4. *Bob* on the other hand sometimes needs to look into other teams releases. When there is something going wrong in the communication with another team's service, his first look is whether something has recently changed there.

5. *Alice* also likes being able to view several team's applications at once. Especially the locks are important to her as she wants to make sure that all teams do frequent releases.

6. *Alice* is frustrated that the release train failed last week and nobody felt responsible because it seen as a "shared responsibility" that "somebody else definitely will take care of".

# Ideas

1. We can tell people to simply have different kuberpult instances. This would make it definitely work, however we would need to install more instances and it would be hard to get a complete overview.

2. We can introduce namespaces for applications. 

3. We could offer some filtering on name prefixes.

# Issues 

- #97 Release train per team

**Comment by sven-urbanski-freiheit-com** [comment]
Some Ideas for stories:
* easy way to select the team, and filter for it (maybe with auto-suggest?)
* save current filter in cookie/local storage for next page refresh
* maybe(?) optimize to load only data from overviewservice that is required for the current filter (might be difficult)

**Comment by hannesg** [comment]
We now have the teams filter in the new UI -> closing for now
